### ISSUE TITLE
while playing any episode when press back button and exit of application and going to it again you will have same exceptions

### ISSUE THREAD

**Issue by Anthony-Sol** [amugofjava/anytime_podcast_player#38]
Hi Ben ,I hope you are well.
while playing any episode when press back button and exit of application and going to it again you will have same exceptions
that it make very problem while using app
**To Reproduce**
1. play any episode
2. Click on back button and exit of application 
3. and going to app again
4. you will have very exception

it is a image of exceptions
![bug](https://user-images.githubusercontent.com/75216006/110303201-5c84bd80-800f-11eb-9523-b76ce69ad218.JPG)

**Comment by amugofjava** [comment]
Thanks for reporting this issue @mohammad-soltani77. A few questions:

1. When you backed out using the back button was the episode playing, paused or stopped?
2. Does this happen every time you exit via the back button or only sometimes?
3. What version of Android are you running on?

Thanks,

Ben.

**Comment by mohammad-soltani77** [comment]
@amugofjava 
if episode was played from net(feed) sometimes that you press back button and exit of app and going to it again ,episode will not stop or pause but miniPlayer will be blank and you will get very exceptions
android version may phone is 8.0.0

here is a video of what I said that I put in dropbox:
https://www.dropbox.com/s/mlymfznrr4hx5px/anytime.mp4?dl=0

**Comment by amugofjava** [comment]
Thanks for the video @mohammad-soltani77. I can now recreate the issues. This back button is proving to be a source of issues.

**Comment by mohammad-soltani77** [comment]
Do you know where the problem comes from?
because when episode was played from download list it is fine(don't have exception and miniPlayer don't be blank ).

**Comment by mohammad-soltani77** [comment]
thanks Ben for answer giving me.
I hope this problem will be solved as soon as possible

**Comment by amugofjava** [comment]
This should now be resolved @mohammad-soltani77. Please let me know if it still errors for you. Thanks.

**Comment by mohammad-soltani77** [comment]
Hi @amugofjava there are still exceptions when you play a episode will get exception.
it is a image of this exception
![bug 5](https://user-images.githubusercontent.com/75216006/111625342-fca5c800-8801-11eb-9ef3-5ceb7bad15c0.JPG)

and previous problem (while playing any episode  when press back button and exit of application and going to it again you will get some exceptions) is still (but miniplayer don't blank) 
it is a image of this exception
![bug 3](https://user-images.githubusercontent.com/75216006/111626665-899d5100-8803-11eb-9830-36ea6be37589.JPG)

**Comment by amugofjava** [comment]
Hi,

I did push an update a little after closing this issue as I found a problem, and I've just pushed another minor improvement. Can you please try again and see if you still get this error? Thanks.

**Comment by mohammad-soltani77** [comment]
this problem is still (while playing any episode when press back button and exit of application and going to it again you will get some exceptions)
you will get previous exception
![bug 3](https://user-images.githubusercontent.com/75216006/111689799-b96b4980-8841-11eb-87b1-ae9111b0bc0b.JPG)

**Comment by amugofjava** [comment]
I'm not sure why this is happening just yet. For now I have wrapped the offending code with a null check to see if that improves things for you. I'll spend some time over the weekend looking into this further.

**Comment by mohammad-soltani77** [comment]
thank you 
best regard

**Comment by amugofjava** [comment]
Hi @mohammad-soltani77,

I have pushed several updates to `master` including moving to Flutter 2. This appears to be fixed, but are you able to test again and see if it's fixed for you? Thanks.

**Comment by mohammad-soltani77** [comment]
Hi @amugofjava 
it is solved (previous problem )
but when you are playing  a episode but when this has not been played if you close it with Miniplayer this will have exception.
here is a image of this exception
![bug](https://user-images.githubusercontent.com/75216006/114376922-5a2bfb00-9b9b-11eb-93f8-8b823bf92178.jpg)
